// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpotXo0m3LPRpJFOVA0pRToUp5t6f8Sio',
    appId: '1:72010637607:web:135f27887129137bd44902',
    messagingSenderId: '72010637607',
    projectId: 'togood-5d7cc',
    authDomain: 'togood-5d7cc.firebaseapp.com',
    databaseURL: 'https://togood-5d7cc-default-rtdb.firebaseio.com',
    storageBucket: 'togood-5d7cc.firebasestorage.app',
    measurementId: 'G-GTCZR6FNLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07tW80O_hmI63WjlQCDgrVVWHIsO0YFc',
    appId: '1:72010637607:android:6fffd8ad57c27a60d44902',
    messagingSenderId: '72010637607',
    projectId: 'togood-5d7cc',
    databaseURL: 'https://togood-5d7cc-default-rtdb.firebaseio.com',
    storageBucket: 'togood-5d7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8oxe6oJCudN8qB2nOxr5ZITZ8H6APyA',
    appId: '1:72010637607:ios:ee647cddbcfea00ed44902',
    messagingSenderId: '72010637607',
    projectId: 'togood-5d7cc',
    databaseURL: 'https://togood-5d7cc-default-rtdb.firebaseio.com',
    storageBucket: 'togood-5d7cc.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8oxe6oJCudN8qB2nOxr5ZITZ8H6APyA',
    appId: '1:72010637607:ios:ee647cddbcfea00ed44902',
    messagingSenderId: '72010637607',
    projectId: 'togood-5d7cc',
    databaseURL: 'https://togood-5d7cc-default-rtdb.firebaseio.com',
    storageBucket: 'togood-5d7cc.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpotXo0m3LPRpJFOVA0pRToUp5t6f8Sio',
    appId: '1:72010637607:web:d38768faadf03489d44902',
    messagingSenderId: '72010637607',
    projectId: 'togood-5d7cc',
    authDomain: 'togood-5d7cc.firebaseapp.com',
    databaseURL: 'https://togood-5d7cc-default-rtdb.firebaseio.com',
    storageBucket: 'togood-5d7cc.firebasestorage.app',
    measurementId: 'G-XEEJS2GEFT',
  );
}
